
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Abandoned Houses.
# 1 for spawning in most chunks and 1001 for none.
[Abandonedhouse]
	#Range: 1 ~ 1001
	abandonedhouseAverageChunkDistance = 65

