
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Castles.
# 1 for spawning in most chunks and 1001 for none.
[Castles]
	#Range: 1 ~ 1001
	castleAverageChunkDistance = 50

