
#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Wizard Towers.
# 1 for spawning in most chunks and 1001 for none.
[Cottages]
	#Range: 1 ~ 1001
	cottageAverageChunkDistance = 40

