
["Gameplay Settings"]
	dropRawOres = true
	monstersSpawnOnlyInTotalDarkness = true

["Ore Generation Settings"]
	generateDeepslateBlobs = true
	generateCopperOre = false
	generateTuffBlobs = true

["World Generation Settings"]

	["World Generation Settings"."Amethyst Geode Settings"]
		generateAmethystGeodes = true
		#Range: > 1
		amethystGeodeChance = 53

	["World Generation Settings"."Glow Lichen Settings"]
		generateGlowLichen = false

	["World Generation Settings"."Cave Biome Settings"]
		generateDripstoneCaves = true
		generateLushCaves = true

["Entity Settings"]

	["Entity Settings"."Glow Squid Settings"]
		#Range: 0 ~ 100
		glowSquidWeight = 0
		generateGlowSquids = false

	["Entity Settings"."Axolotl Settings"]
		#Range: 0 ~ 100
		axolotlWeight = 10
		generateAxolotls = true

	["Entity Settings"."Goat Settings"]
		#Range: 0 ~ 100
		goatWeight = 10
		generateGoats = false

["Experimental Settings"]
	#Range: 0 ~ 256
	deepslateLayerMaxHeight = 0

["World Type Settings"]
	generateNoiseCaves = false
	generateOreVeins = false
	generateDeepslate = true
	generateNoodleCaves = false
	generateAquifers = false

