
[General]
	#Allows players to view the precise coordinates and distance of a located structure on the HUD, rather than relying on the direction the compass is pointing.
	displayCoordinates = false
	#biomeSize * sampleSpaceModifier = sampleSpace. Lowering this value will increase search accuracy but will make the process more resource intensive.
	#Range: 0 ~ 1000000
	sampleSpaceModifier = 16
	#Allows a player to teleport to a located biome when in creative mode, opped, or in cheat mode.
	allowTeleport = true
	#The maximum number of samples to be taken when searching for a biome.
	#Range: 0 ~ 1000000
	maxSamples = 50000
	#A list of biomes that the compass will not be able to search for, specified by resource location. The wildcard character * can be used to match any number of characters, and ? can be used to match one character. Ex: ["minecraft:savanna", "minecraft:desert", "minecraft:*ocean*"]
	biomeBlacklist = ["betterendforge:empty_aurora_cave", "betterendforge:empty_end_cave", "betterendforge:empty_smaragdant_cave", "betterendforge:lush_aurora_cave", "betterendforge:lush_smaragdant_cave", "biomesoplenty:bamboo_blossom_grove", "biomesoplenty:bayou_mangrove", "biomesoplenty:burnt_forest", "biomesoplenty:cold_desert", "terraforged:cold_marshland", "biomesoplenty:coniferous_lakes", "biomesoplenty:deep_bayou", "biomesoplenty:dense_marsh", "biomesoplenty:dense_woodland", "biomesoplenty:fir_clearing", "biomesoplenty:flower_meadow", "terraforged:frozen_marsh", "biomesoplenty:fungal_field", "biomesoplenty:meadow_forest", "biomesoplenty:highland_moor", "biomesoplenty:lavender_forest", "biomesoplenty:mystic_plains", "biomesoplenty:ominous_mire", "biomesoplenty:rainforest_cliffs", "biomesoplenty:rainforest_floodplain", "biomesoplenty:redwood_hills", "biomesoplenty:seasonal_orchard", "biomesoplenty:seasonal_pumpkin_patch", "biomesoplenty:shroomy_wetland", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:snowy_fir_clearing", "biomesoplenty:snowy_maple_forest", "biomesoplenty:tall_dead_forest", "terraforged:marshland"]
	#biomeSize * radiusModifier = maxSearchRadius. Raising this value will increase search accuracy but will potentially make the process more resource .
	#Range: 0 ~ 1000000
	radiusModifier = 2500

