
[general]
	#Range: 0.0 ~ 1.0
	dark_nether_fog = 0.5
	only_affect_block_light = true
	#Range: 0.0 ~ 1.0
	dark_end_fog = 0.0
	dark_overworld = false
	#Range: 0.0 ~ 1.0
	minimum_moon_brightness = 0.0
	#Range: 0.0 ~ 1.0
	maximum_moon_brightness = 1.0
	dark_default = false
	dark_end = false
	dark_skyless = false
	dark_nether = false
	#Range: 0.0 ~ 1.0
	minimum_light = 0.0
	ignore_moon_phase = false

